### ISSUE TITLE
Traceback , ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

### ISSUE THREAD

**Issue by d0rb** [N0rz3/Zehef#2]
Any Idea about this traceback error? stack's answer seems messy with the ssl config.
I'm using debian.

```
Traceback (most recent call last):
  File "/home/sup/Downloads/Zehef/modules/account.py", line 66, in check_email
    await asyncio.gather(*tasks)
  File "/home/sup/Downloads/Zehef/modules/account.py", line 54, in run_module
    await module(email, client, out)
  File "/usr/local/lib/python3.10/dist-packages/holehe/modules/sport/bodybuilding.py", line 21, in bodybuilding
    response = await client.head('https://api.bodybuilding.com/profile/email/' + email, headers=headers)
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1809, in head
    return await self.request(
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/lib/python3/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/usr/lib/python3/dist-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/usr/lib/python3/dist-packages/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/usr/lib/python3/dist-packages/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/lib/python3/dist-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

During handling of the above exception, another exception occurred:
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)
Traceback (most recent call last):
  File "/home/sup/Downloads/Zehef/zehef.py", line 2, in <module>
    import main; main.version()
  File "/home/sup/Downloads/Zehef/main.py", line 11, in version
    loop.run_until_complete(CLI.parser())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/sup/Downloads/Zehef/lib/CLI.py", line 29, in parser
    await main.zehef(email)
  File "/home/sup/Downloads/Zehef/output/main.py", line 32, in zehef
    await account.check_email(email)
  File "/home/sup/Downloads/Zehef/modules/account.py", line 57, in check_email
    async with httpx.AsyncClient() as client:
  File "/usr/lib/python3/dist-packages/httpx/_client.py", line 1997, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/usr/lib/python3/dist-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/usr/lib/python3/dist-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 14 HTTP requests/responses were still in-flight.

```

**Comment by N0rz3** [comment]
I'm sorry but I have no explanation for this error. Maybe someone more experienced than me can help you out and fix the problem.

from what i know, it is a error with a module of holehe and I don't think debian is the cause of the problem.

**Comment by MasterChad** [comment]
Maybe it's your ip adress, try vpn
or if you have Burp or other things like that, try to disable it

If you are on VPS, maybe your VPS use the IPV6, u can edit the network conf for remove ipv6 and stay with the ipv4

**Comment by corvus-migratorius** [comment]
> 

Same issue, tried multiple VPN servers, -- no joy (Ubuntu 18.04).

**Comment by jiapei100** [comment]
Same here... Just about to throw out this issue...


```console
😈 Account Checker

Traceback (most recent call last):
  File "....../Zehef/zehef.py", line 3, in <module>
    import main; main.version()
  File "....../Zehef/main.py", line 11, in version
    loop.run_until_complete(CLI.parser())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "....../Zehef/lib/CLI.py", line 29, in parser
    await main.zehef(email)
  File "....../Zehef/output/main.py", line 32, in zehef
    await account.check_email(email)
  File "....../Zehef/modules/account.py", line 69, in check_email
    await asyncio.gather(*tasks)
  File "....../Zehef/modules/account.py", line 55, in run_module
    await module(email, client, out)
  File "~.local/lib/python3.10/site-packages/holehe/modules/sport/bodybuilding.py", line 21, in bodybuilding
    response = await client.head('https://api.bodybuilding.com/profile/email/' + email, headers=headers)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1815, in head
    return await self.request(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "~.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 149, in _connect
    stream = await stream.start_tls(**kwargs)
  File "~.local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "~.local/lib/python3.10/site-packages/anyio/streams/tls.py", line 123, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "~.local/lib/python3.10/site-packages/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)
```

**Comment by TimTProd** [comment]
@jiapei100 are you on the newest branch? I think that this problem should be already solved by #5

**Comment by N0rz3** [comment]
ohh I'm really sorry at some bones there is this error, I don't know why I'm working to fix this

for the moment try to upgrade holehe with this command: `pip install --upgrade holehe`

**Comment by N0rz3** [comment]
I just modified the file `account.py` I don't know if this will solve your error

**Comment by jiapei100** [comment]
@N0rz3 

You may want to add `pip install scrape-search-engine` in your requirements.txt .

Even if I checked out your NEWEST commit, I still have this issue:

```console
😈 Account Checker

Traceback (most recent call last):
  File "....../Zehef/zehef.py", line 3, in <module>
    import main; main.version()
  File "....../Zehef/main.py", line 11, in version
    loop.run_until_complete(CLI.parser())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "....../Zehef/lib/CLI.py", line 29, in parser
    await main.zehef(email)
  File "....../Zehef/output/main.py", line 34, in zehef
    await account.check_email(email)
  File "....../Zehef/modules/account.py", line 79, in check_email
    await asyncio.gather(*tasks)
  File "....../Zehef/modules/account.py", line 65, in run_module
    await module(email, client, out)
  File "~.local/lib/python3.10/site-packages/holehe/modules/sport/bodybuilding.py", line 21, in bodybuilding
    response = await client.head('https://api.bodybuilding.com/profile/email/' + email, headers=headers)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1815, in head
    return await self.request(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "~.local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "~.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
  File "~.local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 149, in _connect
    stream = await stream.start_tls(**kwargs)
  File "~.local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 78, in start_tls
    raise exc
  File "~.local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "~.local/lib/python3.10/site-packages/anyio/streams/tls.py", line 123, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "~.local/lib/python3.10/site-packages/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)
```

**Comment by N0rz3** [comment]
for the moment just remove the `account` module you will just have the account search functionality associated with the email in less

**Comment by N0rz3** [comment]
If you don't know how to do it, let me know and I'll explain it to you.

**Comment by N0rz3** [comment]
try again now and let me know if the problem still persists
